In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly.express as px 
import plotly.graph_objects as go 
import plotly.io as pio

In [2]:
df_proc = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test_Processed.csv')

In [4]:
df_proc.tail()

,sample_id,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_56699_0,SNP_56699_1,SNP_56699_2,SNP_56700_0,SNP_56700_1,SNP_56700_2,SNP_56700_3,SNP_56716_0,SNP_56716_1,SNP_56716_2
113,GCA_025788045.2,0,1,0,1,0,0,1,0,0,...,False,False,True,False,False,True,0,0,0,0
114,GCA_025788255.2,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
115,GCA_025788655.2,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
116,GCA_025789775.2,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
117,GCA_025789855.2,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0

In [3]:
df_train = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPData/SNP_merged_train.csv')
df_test = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test_Processed.csv')

In [4]:
df_train.shape, df_test.shape

((470, 56719), (118, 56719))

In [4]:
df_train.head()

,sample_id,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_56708,SNP_56709,SNP_56710,SNP_56711,SNP_56712,SNP_56713,SNP_56714,SNP_56715,SNP_56716,label
0,GCA_023891605.1,0,0,0,1,1,0,1,1,1,...,0,1,1,1,0,1,1,0,2,R
1,GCA_023883465.1,0,0,0,1,1,0,1,1,1,...,0,1,1,1,0,1,1,0,2,R
2,ERR4036809,0,0,0,0,1,0,1,1,1,...,0,1,1,1,1,0,1,0,1,R
3,ERR4035165,0,0,0,1,1,0,1,1,1,...,0,1,1,1,0,1,1,0,1,S
4,ERR4034138,0,1,0,1,0,0,1,0,0,...,0,0,0,1,0,1,1,1,1,S

In [ ]:
df_test.head()

,sample_id,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_56708,SNP_56709,SNP_56710,SNP_56711,SNP_56712,SNP_56713,SNP_56714,SNP_56715,SNP_56716,label
0,GCA_025789855.2,0,0,0,0,1,0,1,1,1,...,0,1,1,1,0,1,1,0,1,S
1,ERR4035462,0,0,0,1,1,0,1,1,1,...,0,1,1,1,0,1,1,0,2,R
2,GCA_025782975.2,0,0,0,0,1,0,1,1,1,...,0,0,1,1,0,1,1,0,1,R
3,ERR1218605,0,0,0,1,0,0,1,0,0,...,0,0,1,1,0,1,1,1,1,R
4,GCA_023881545.1,0,0,0,1,1,0,1,1,1,...,0,1,1,1,1,0,1,0,1,S

:

In [2]:
df = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPRepData/SNP_merged_test.csv')

In [ ]:
df.head()

,sample_id,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_56708,SNP_56709,SNP_56710,SNP_56711,SNP_56712,SNP_56713,SNP_56714,SNP_56715,SNP_56716,label
0,GCA_025789855.2,0,0,0,0,1,0,1,1,1,...,0,1,1,1,0,1,1,0,1,S
1,ERR4035462,0,0,0,1,1,0,1,1,1,...,0,1,1,1,0,1,1,0,2,R
2,GCA_025782975.2,0,0,0,0,1,0,1,1,1,...,0,0,1,1,0,1,1,0,1,R
3,ERR1218605,0,0,0,1,0,0,1,0,0,...,0,0,1,1,0,1,1,1,1,R
4,GCA_023881545.1,0,0,0,1,1,0,1,1,1,...,0,1,1,1,1,0,1,0,1,S

## Exploring the Processed Test File (Last CSV fed to model)

This is the file that caused the NaN error during model evaluation.

In [3]:
# Load the processed test file that was fed to the model
processed_file = '/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test_Processed.csv'

df_processed = pd.read_csv(processed_file)
print(f"Shape: {df_processed.shape}")
print(f"\nColumns: {len(df_processed.columns)}")
print(f"\nFirst few column names: {list(df_processed.columns[:10])}")
print(f"\nLast few column names: {list(df_processed.columns[-10])}")

Shape: (118, 67261)

Columns: 67261

First few column names: ['sample_id', 'SNP_0', 'SNP_1', 'SNP_2', 'SNP_3', 'SNP_4', 'SNP_5', 'SNP_6', 'SNP_7', 'SNP_8']

Last few column names: ['S', 'N', 'P', '_', '5', '6', '6', '9', '9', '_', '0']

In [4]:
# Check for NaN values - THIS IS THE ISSUE!
print("=== NaN Analysis ===")
print(f"Total NaN values: {df_processed.isna().sum().sum()}")
print(f"Rows with any NaN: {df_processed.isna().any(axis=1).sum()}")
print(f"Columns with any NaN: {df_processed.isna().any(axis=0).sum()}")

# Find columns with NaN
nan_cols = df_processed.columns[df_processed.isna().any()].tolist()
if len(nan_cols) > 0:
    print(f"\nColumns with NaN ({len(nan_cols)}):")
    for col in nan_cols[:20]:  # Show first 20
        nan_count = df_processed[col].isna().sum()
        print(f"  {col}: {nan_count} NaNs ({nan_count/len(df_processed)*100:.2f}%)")
    if len(nan_cols) > 20:
        print(f"  ... and {len(nan_cols) - 20} more columns")
else:
    print("No NaN values found!")

=== NaN Analysis ===
Total NaN values: 470
Rows with any NaN: 47
Columns with any NaN: 433

Columns with NaN (433):
  SNP_82: 1 NaNs (0.85%)
  SNP_196: 1 NaNs (0.85%)
  SNP_490: 1 NaNs (0.85%)
  SNP_603: 1 NaNs (0.85%)
  SNP_795: 1 NaNs (0.85%)
  SNP_1252: 1 NaNs (0.85%)
  SNP_1424: 1 NaNs (0.85%)
  SNP_1694: 1 NaNs (0.85%)
  SNP_1838: 1 NaNs (0.85%)
  SNP_1935: 1 NaNs (0.85%)
  SNP_2061: 1 NaNs (0.85%)
  SNP_2295: 1 NaNs (0.85%)
  SNP_2342: 1 NaNs (0.85%)
  SNP_2423: 1 NaNs (0.85%)
  SNP_2513: 1 NaNs (0.85%)
  SNP_2566: 1 NaNs (0.85%)
  SNP_2923: 1 NaNs (0.85%)
  SNP_2932: 1 NaNs (0.85%)
  SNP_2973: 1 NaNs (0.85%)
  SNP_3063: 1 NaNs (0.85%)
  ... and 413 more columns

In [5]:
# Check data types
print("=== Data Type Analysis ===")
print(df_processed.dtypes.value_counts())
print("\nColumns with boolean type:")
bool_cols = df_processed.select_dtypes(include=['bool']).columns.tolist()
print(f"  {len(bool_cols)} boolean columns")
if len(bool_cols) > 0:
    print(f"  Examples: {bool_cols[:5]}")
    
print("\nColumns with object type:")
obj_cols = df_processed.select_dtypes(include=['object']).columns.tolist()
print(f"  {len(obj_cols)} object columns")
if len(obj_cols) > 0:
    print(f"  Examples: {obj_cols[:5]}")

=== Data Type Analysis ===
int64      56632
bool       10195
float64      433
object         1
Name: count, dtype: int64

Columns with boolean type:
  10195 boolean columns
  Examples: ['SNP_29_0', 'SNP_29_1', 'SNP_29_2', 'SNP_67_0', 'SNP_67_1']

Columns with object type:
  1 object columns
  Examples: ['sample_id']

In [6]:
# Check for infinite values and other problematic values
print("=== Problematic Values Check ===")
import numpy as np

# Check for inf values
inf_cols = []
for col in df_processed.select_dtypes(include=[np.number]).columns:
    if np.isinf(df_processed[col]).any():
        inf_cols.append(col)
        print(f"  {col}: {np.isinf(df_processed[col]).sum()} inf values")

if len(inf_cols) == 0:
    print("No infinite values found")

# Check unique value counts for first few columns
print("\n=== Unique Values in First 10 Columns ===")
for col in df_processed.columns[:10]:
    unique_vals = df_processed[col].unique()
    print(f"{col}: {len(unique_vals)} unique values - {sorted(unique_vals[:10])}")

=== Problematic Values Check ===
No infinite values found

=== Unique Values in First 10 Columns ===
sample_id: 118 unique values - ['ERR1218605', 'ERR1218646', 'ERR4034045', 'ERR4035462', 'ERR434405', 'ERR434515', 'GCA_023881545.1', 'GCA_023887165.1', 'GCA_025782975.2', 'GCA_025789855.2']
SNP_0: 2 unique values - [0, 1]
SNP_1: 2 unique values - [0, 1]
SNP_2: 2 unique values - [0, 1]
SNP_3: 2 unique values - [0, 1]
SNP_4: 2 unique values - [0, 1]
SNP_5: 2 unique values - [0, 1]
SNP_6: 2 unique values - [0, 1]
SNP_7: 2 unique values - [0, 1]
SNP_8: 2 unique values - [0, 1]

In [7]:
# Detailed view of rows/columns with NaN
if df_processed.isna().any().any():
    print("=== Detailed NaN Analysis ===")
    
    # Show rows with NaN
    rows_with_nan = df_processed[df_processed.isna().any(axis=1)]
    print(f"\nRows with NaN: {len(rows_with_nan)}")
    print(f"Sample rows with NaN (first 5):")
    print(rows_with_nan.head())
    
    # Show which specific cells have NaN
    print("\nNaN locations (first 20):")
    nan_mask = df_processed.isna()
    nan_locations = []
    for idx in nan_mask.index[:20]:
        cols_with_nan = nan_mask.columns[nan_mask.loc[idx]].tolist()
        if cols_with_nan:
            nan_locations.append((idx, cols_with_nan[:5]))  # First 5 columns per row
    
    for idx, cols in nan_locations[:10]:
        print(f"  Row {idx}: {len(cols)} columns with NaN - {cols}")

=== Detailed NaN Analysis ===

Rows with NaN: 47
Sample rows with NaN (first 5):
          sample_id  SNP_0  SNP_1  SNP_2  SNP_3  SNP_4  SNP_5  SNP_6  SNP_7  \
0   GCA_025789855.2      0      0      0      0      1      0      1      1
3        ERR1218605      0      0      0      1      0      0      1      0
4   GCA_023881545.1      0      0      0      1      1      0      1      1
5         ERR434515      1      1      1      1      0      0      1      0
11        ERR435456      0      0      0      1      1      0      1      1

    SNP_8  ...  SNP_56699_0  SNP_56699_1  SNP_56699_2  SNP_56700_0  \
0       1  ...        False         True        False        False
3       0  ...        False        False         True        False
4       1  ...        False         True        False        False
5       0  ...        False         True        False        False
11      1  ...        False         True        False        False

    SNP_56700_1  SNP_56700_2  SNP_56700_3  SNP_56716_0  SNP_56716_1  \
0          True        False            0            0            0
3         False         True            0            0            0
4          True        False            0            0            0
5          True        False            0            0            0
11         True        False            0            0            0

    SNP_56716_2
0             0
3             0
4             0
5             0
11            0

[5 rows x 67261 columns]

NaN locations (first 20):
  Row 0: 5 columns with NaN - ['SNP_8534', 'SNP_14609', 'SNP_34837', 'SNP_35260', 'SNP_35264']
  Row 3: 1 columns with NaN - ['SNP_40369']
  Row 4: 5 columns with NaN - ['SNP_4757', 'SNP_6274', 'SNP_6296', 'SNP_10002', 'SNP_16064']
  Row 5: 2 columns with NaN - ['SNP_2423', 'SNP_12250']
  Row 11: 1 columns with NaN - ['SNP_6093']
  Row 12: 4 columns with NaN - ['SNP_28615', 'SNP_38001', 'SNP_43745', 'SNP_47492']
  Row 13: 5 columns with NaN - ['SNP_196', 'SNP_795', 'SNP_1424', 'SNP_2061', 'SNP_2295']
  Row 14: 2 columns with NaN - ['SNP_32306', 'SNP_51370']
  Row 18: 2 columns with NaN - ['SNP_10544', 'SNP_39243']

In [8]:
# Check if there's a label column
print("=== Label Column Check ===")
if 'label' in df_processed.columns:
    print(f"Label column found!")
    print(f"Label distribution:\n{df_processed['label'].value_counts()}")
elif 'Class' in df_processed.columns:
    print(f"Class column found!")
    print(f"Class distribution:\n{df_processed['Class'].value_counts()}")
else:
    print("No label/Class column found")
    print(f"Column names containing 'label' or 'class': {[c for c in df_processed.columns if 'label' in c.lower() or 'class' in c.lower()]}")

=== Label Column Check ===
Label column found!
Label distribution:
label
0    63
1    55
Name: count, dtype: int64

In [9]:
# Summary statistics
print("=== Summary Statistics ===")
print(f"Total cells: {df_processed.shape[0] * df_processed.shape[1]}")
print(f"NaN cells: {df_processed.isna().sum().sum()}")
print(f"NaN percentage: {df_processed.isna().sum().sum() / (df_processed.shape[0] * df_processed.shape[1]) * 100:.4f}%")

# Memory usage
print(f"\nMemory usage: {df_processed.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

=== Summary Statistics ===
Total cells: 7936798
NaN cells: 470
NaN percentage: 0.0059%

Memory usage: 52.53 MB

## Configuration Analysis & Available Techniques for Handling NaN Values

Based on your current configuration (`Abdoul_configs.cfg`), here are the available techniques:

In [10]:
# Read and display current configuration
import configparser

config_path = '/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/run_configs/Abdoul_configs.cfg'
config = configparser.ConfigParser()
config.read(config_path)

print("=== Current Configuration Settings ===")
print("\n[Imputing and Scaling - Phase 2]")
print(f"  impute_data = {config.get('imputing and scaling - phase 2', 'impute_data')}")
print(f"  scale_data = {config.get('imputing and scaling - phase 2', 'scale_data')}")
print(f"  multi_impute = {config.get('imputing and scaling - phase 2', 'multi_impute')}")
print(f"  overwrite_cv = {config.get('imputing and scaling - phase 2', 'overwrite_cv')}")

print("\n[Data Processing - Phase 1]")
print(f"  cleaning_missingness = {config.get('data processing - phase 1', 'cleaning_missingness')}")
print(f"  featureeng_missingness = {config.get('data processing - phase 1', 'featureeng_missingness')}")

=== Current Configuration Settings ===

[Imputing and Scaling - Phase 2]
  impute_data = True
  scale_data = False
  multi_impute = False
  overwrite_cv = False

[Data Processing - Phase 1]
  cleaning_missingness = 1.0
  featureeng_missingness = 1.0

### Available Techniques for Handling NaN Values

#### 1. **Configuration-Based Techniques (STREAMLINE Built-in)**

**A. Imputation Settings:**
- **`impute_data = True`**: Enables imputation (currently ON ✅)
- **`multi_impute = False`**: Uses simple median imputation (currently OFF)
  - When `True`: Uses IterativeImputer (MICE - Multiple Imputation by Chained Equations)
  - When `False`: Uses median for quantitative, mode for categorical
- **`scale_data = False`**: Feature scaling disabled (currently OFF)

**B. Missingness Thresholds:**
- **`cleaning_missingness = 1.0`**: Features with >100% missing removed (currently allows all)
- **`featureeng_missingness = 1.0`**: Missingness threshold for feature engineering

#### 2. **Imputation Methods Available:**

**For Categorical Features:**
- Mode imputation (most frequent value)
- Fallback to 0 if all values are NaN

**For Quantitative Features:**
- **Simple**: Median imputation (current setting)
- **Advanced**: IterativeImputer (MICE) - when `multi_impute = True`
  - Uses Bayesian Ridge regression
  - Multiple iterations to converge
  - More accurate but slower

#### 3. **Alternative Techniques (Manual Implementation):**

In [5]:
# Technique 1: Simple Forward Fill / Backward Fill
def forward_fill_nan(df):
    """Fill NaN with previous value in column"""
    return df.fillna(method='ffill').fillna(method='bfill')

# Technique 2: Mean/Median/Mode Imputation
def simple_impute(df, strategy='median'):
    """Simple imputation using mean, median, or mode"""
    from sklearn.impute import SimpleImputer
    
    # Separate numeric and categorical
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    categorical_cols = df.select_dtypes(include=['object', 'bool']).columns
    
    imputed_df = df.copy()
    
    # Impute numeric with mean/median
    if len(numeric_cols) > 0:
        numeric_imputer = SimpleImputer(strategy=strategy)
        imputed_df[numeric_cols] = numeric_imputer.fit_transform(df[numeric_cols])
    
    # Impute categorical with mode
    if len(categorical_cols) > 0:
        categorical_imputer = SimpleImputer(strategy='most_frequent')
        imputed_df[categorical_cols] = categorical_imputer.fit_transform(df[categorical_cols])
    
    return imputed_df

# Technique 3: KNN Imputation
def knn_impute(df, n_neighbors=5):
    """K-Nearest Neighbors imputation"""
    from sklearn.impute import KNNImputer
    
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    imputed_df = df.copy()
    
    if len(numeric_cols) > 0:
        knn_imputer = KNNImputer(n_neighbors=n_neighbors)
        imputed_df[numeric_cols] = knn_imputer.fit_transform(df[numeric_cols])
    
    return imputed_df

# Technique 4: Iterative Imputation (MICE)
def iterative_impute(df):
    """Iterative Imputation using MICE"""
    from sklearn.experimental import enable_iterative_imputer
    from sklearn.impute import IterativeImputer
    
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    imputed_df = df.copy()
    
    if len(numeric_cols) > 0:
        iterative_imputer = IterativeImputer(random_state=42, max_iter=10)
        imputed_df[numeric_cols] = iterative_imputer.fit_transform(df[numeric_cols])
    
    return imputed_df

# Technique 5: Drop rows/columns with NaN
def drop_nan(df, axis=0, thresh=None):
    """Drop rows (axis=0) or columns (axis=1) with NaN"""
    if thresh:
        return df.dropna(axis=axis, thresh=thresh)
    return df.dropna(axis=axis)

print("Imputation functions defined!")

Imputation functions defined!

In [9]:
# Fix: Redefine simple_impute to handle boolean columns properly
def simple_impute(df, strategy='median'):
    """Simple imputation using mean, median, or mode - FIXED VERSION"""
    from sklearn.impute import SimpleImputer
    
    # Separate numeric, boolean, and object categorical
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    bool_cols = df.select_dtypes(include=['bool']).columns.tolist()
    object_cols = df.select_dtypes(include=['object']).columns.tolist()
    
    imputed_df = df.copy()
    
    # Impute numeric with mean/median
    if len(numeric_cols) > 0:
        numeric_imputer = SimpleImputer(strategy=strategy)
        imputed_df[numeric_cols] = numeric_imputer.fit_transform(df[numeric_cols])
    
    # Impute boolean columns manually (SimpleImputer doesn't support bool)
    for col in bool_cols:
        if imputed_df[col].isna().sum() > 0:
            mode_val = imputed_df[col].mode()
            fill_val = mode_val[0] if len(mode_val) > 0 else False
            imputed_df[col] = imputed_df[col].fillna(fill_val)
    
    # Impute object categorical with mode
    if len(object_cols) > 0:
        categorical_imputer = SimpleImputer(strategy='most_frequent')
        imputed_df[object_cols] = categorical_imputer.fit_transform(df[object_cols])
    
    return imputed_df

print("✅ simple_impute function fixed to handle boolean columns!")

✅ simple_impute function fixed to handle boolean columns!

In [ ]:
# Test different imputation techniques on the processed data
print("=== Testing Imputation Techniques ===\n")

# Make a copy for testing
df_test_impute = df_test.copy()

# Remove sample_id and label for imputation (we'll add them back)
sample_ids = df_test_impute['sample_id']
labels = df_test_impute['label'] if 'label' in df_test_impute.columns else None
df_features = df_test_impute.drop(['sample_id', 'label'], axis=1, errors='ignore')

print(f"Original NaN count: {df_features.isna().sum().sum()}")

# Technique 1: Simple Median/Mode
print("\n1. Simple Median/Mode Imputation:")
df_simple = simple_impute(df_features.copy(), strategy='median')
print(f"   NaN after imputation: {df_simple.isna().sum().sum()}")

# # Technique 2: Forward Fill
# print("\n2. Forward Fill:")
# df_ffill = forward_fill_nan(df_features.copy())
# print(f"   NaN after imputation: {df_ffill.isna().sum().sum()}")

# # Technique 3: KNN Imputation (may be slow for large datasets)
# print("\n3. KNN Imputation (n_neighbors=5):")
# try:
#     df_knn = knn_impute(df_features.copy(), n_neighbors=5)
#     print(f"   NaN after imputation: {df_knn.isna().sum().sum()}")
# except Exception as e:
#     print(f"   Error: {e}")

# # Technique 4: Iterative Imputation (MICE) - may be slow
# print("\n4. Iterative Imputation (MICE):")
# try:
#     df_iterative = iterative_impute(df_features.copy())
#     print(f"   NaN after imputation: {df_iterative.isna().sum().sum()}")
# except Exception as e:
#     print(f"   Error: {e}")

=== Testing Imputation Techniques ===

Original NaN count: 470

1. Simple Median/Mode Imputation:
   NaN after imputation: 0

In [11]:
# Save the fixed file
df_simple_with_labels = pd.concat([
    pd.DataFrame({'sample_id': sample_ids}),
    df_simple,
    pd.DataFrame({'label': labels}) if labels is not None else pd.DataFrame()
], axis=1)

output_path = '/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test_Processed_FIXED.csv'
df_simple_with_labels.to_csv(output_path, index=False)
print(f"✅ Fixed file saved!")

✅ Fixed file saved!

In [14]:
df_fix = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test_Processed_FIXED.csv')

In [15]:
df_fix.head()

,sample_id,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_56699_1,SNP_56699_2,SNP_56700_0,SNP_56700_1,SNP_56700_2,SNP_56700_3,SNP_56716_0,SNP_56716_1,SNP_56716_2,label
0,GCA_025789855.2,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,...,True,False,False,True,False,0.0,0.0,0.0,0.0,0
1,ERR4035462,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,...,True,False,False,True,False,0.0,0.0,0.0,0.0,1
2,GCA_025782975.2,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,...,True,False,False,True,False,0.0,0.0,0.0,0.0,1
3,ERR1218605,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,False,True,False,False,True,0.0,0.0,0.0,0.0,1
4,GCA_023881545.1,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,...,True,False,False,True,False,0.0,0.0,0.0,0.0,0

In [16]:
df_fix.isna().sum().sum()

0

In [19]:
df_fix.shape

(118, 67261)

### Recommended Solutions for Your NaN Problem

Based on your data (470 NaN values across 433 columns, 0.0059% missing):

**Option 1: Enable Multi-Impute (Recommended)**
- Set `multi_impute = True` in config
- Uses IterativeImputer (MICE) for better accuracy
- Handles complex missing patterns

**Option 2: Fix Imputation in Replication Phase**
- The issue occurs during replication when new values appear
- Add explicit NaN handling before model evaluation
- Use mode for categorical, median for quantitative

**Option 3: Pre-process Test Data**
- Clean test data before feeding to STREAMLINE
- Replace unexpected values (0, 1, 2 in binary features) with mode
- Ensure all features match training data format

**Option 4: Use Models That Handle NaN**
- Switch to algorithms that handle NaN natively:
  - `HistGradientBoostingClassifier` (sklearn)
  - `XGBoost` with `missing` parameter
  - `LightGBM` with `missing` parameter

In [ ]:
# Quick fix: Apply simple imputation to the processed file
print("=== Applying Quick Fix: Simple Imputation ===")

# Load processed file
df_fixed = df_processed.copy()

# Separate features and labels
feature_cols = [c for c in df_fixed.columns if c not in ['sample_id', 'label']]
df_features_only = df_fixed[feature_cols]

# Identify categorical vs quantitative
# Based on data types: bool = categorical, int64/float64 = quantitative
categorical_cols = df_features_only.select_dtypes(include=['bool']).columns.tolist()
quantitative_cols = df_features_only.select_dtypes(include=[np.number]).columns.tolist()

print(f"Categorical columns: {len(categorical_cols)}")
print(f"Quantitative columns: {len(quantitative_cols)}")

# Impute categorical with mode
for col in categorical_cols:
    if df_features_only[col].isna().sum() > 0:
        mode_val = df_features_only[col].mode()
        fill_val = mode_val[0] if len(mode_val) > 0 else False  # Default to False for bool
        df_features_only[col].fillna(fill_val, inplace=True)

# Impute quantitative with median
for col in quantitative_cols:
    if df_features_only[col].isna().sum() > 0:
        median_val = df_features_only[col].median()
        fill_val = median_val if not pd.isna(median_val) else 0
        df_features_only[col].fillna(fill_val, inplace=True)

# Recombine
df_fixed[feature_cols] = df_features_only

print(f"\nNaN count after imputation: {df_fixed.isna().sum().sum()}")
print(f"✅ All NaN values handled!")

# Optionally save the fixed file
# output_path = '/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test_Processed_FIXED.csv'
# df_fixed.to_csv(output_path, index=False)
# print(f"\nFixed file saved to: {output_path}")

=== Applying Quick Fix: Simple Imputation ===
Categorical columns: 10195
Quantitative columns: 57064

/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_features_only[col].fillna(fill_val, inplace=True)
/tmp/ipykernel_2918508/2222267418.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.


NaN count after imputation: 0
✅ All NaN values handled!

## Why Test Data Has NaN But Training Didn't

**The Key Difference:**

### During Training (Phase 1-2):
1. ✅ Data is loaded fresh - all values (0, 1, 2) are valid
2. ✅ Features are identified as binary or multi-category based on unique values
3. ✅ Multi-category features (with 3+ values) get **one-hot encoded** automatically
4. ✅ Binary features (with 2 values) stay as-is
5. ✅ Missing values are imputed normally

### During Replication/Test (Phase 8):
1. ⚠️ STREAMLINE loads the **binary_categorical_dict** from training
2. ⚠️ It expects binary features to have **EXACTLY** the same values as training
3. ⚠️ If a binary feature has a NEW value (like `2` when training only had `0` and `1`), it gets **replaced with NaN**
4. ⚠️ This happens in `model_replicate.py` lines 164-173
5. ⚠️ These NaN values are created AFTER data load but BEFORE imputation
6. ❌ **The imputation should handle them, but some slip through!**

**The Root Cause:**
- Your original data has features with values `{0, 1, 2}` 
- During training, these were identified as "binary" (probably because they had mostly 0/1 with occasional 2)
- During test, when value `2` appears, STREAMLINE sees it as "unexpected" and replaces with NaN
- The imputation code has fallback logic (lines 576-595) but it's not catching all cases

**Solution:** Ensure imputation runs properly on ALL NaN values before model evaluation.

In [ ]:
# Let's verify this theory - check if training data had these values
print("=== Comparing Training vs Test Data ===")

# Load training data
train_file = '/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/CVDatasets/SNP_merged_train_CV_0_Train.csv'
df_train_orig = pd.read_csv(train_file)

# Check some of the problematic SNPs in training data
problematic_snps = ['SNP_82', 'SNP_196', 'SNP_490', 'SNP_603', 'SNP_795']

print("\nTraining Data - Unique values in problematic SNPs:")
for snp in problematic_snps:
    if snp in df_train_orig.columns:
        unique_vals = sorted(df_train_orig[snp].unique())
        print(f"  {snp}: {unique_vals} (count: {len(unique_vals)})")

print("\nTest Data - Unique values in problematic SNPs:")
for snp in problematic_snps:
    if snp in df_test.columns:
        unique_vals = sorted(df_test[snp].unique())
        print(f"  {snp}: {unique_vals} (count: {len(unique_vals)})")

# Check if training had value 2 in these columns
print("\n=== Checking for value '2' in training data ===")
for snp in problematic_snps[:5]:  # Check first 5
    if snp in df_train_orig.columns:
        has_2 = (df_train_orig[snp] == 2).any()
        count_2 = (df_train_orig[snp] == 2).sum()
        print(f"  {snp}: Has value 2? {has_2}, Count: {count_2}")

=== Comparing Training vs Test Data ===

Training Data - Unique values in problematic SNPs:

Test Data - Unique values in problematic SNPs:

NameError: name 'df_test' is not defined

In [ ]:
# Check the binary_categorical_dict from training to see what STREAMLINE expects
import pickle
import os

binary_dict_path = '/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/exploratory/binary_categorical_dict.pickle'

if os.path.exists(binary_dict_path):
    with open(binary_dict_path, 'rb') as f:
        binary_categorical_dict = pickle.load(f)
    
    print("=== Binary Categorical Dictionary from Training ===")
    print(f"Total binary features: {len(binary_categorical_dict)}")
    
    # Check the problematic SNPs
    print("\nExpected values for problematic SNPs:")
    for snp in problematic_snps:
        if snp in binary_categorical_dict:
            expected_vals = sorted(binary_categorical_dict[snp])
            print(f"  {snp}: Expected values = {expected_vals}")
            
            # Check what test data actually has
            if snp in df_test.columns:
                actual_vals = sorted([x for x in df_test[snp].unique() if pd.notna(x)])
                new_vals = set(actual_vals) - set(expected_vals)
                if new_vals:
                    print(f"    ❌ Test has NEW values: {sorted(new_vals)}")
                else:
                    print(f"    ✅ Test values match: {actual_vals}")
else:
    print(f"Binary categorical dict not found at: {binary_dict_path}")

=== Binary Categorical Dictionary from Training ===
Total binary features: 51561

Expected values for problematic SNPs:
  SNP_82: Expected values = [1, 2]

NameError: name 'df_test' is not defined

### The Fix: Ensure Complete Imputation

The issue is that NaN values created during replication need to be properly imputed. The code has fallback logic, but we need to ensure it runs correctly. Here are the solutions:

In [ ]:
# SOLUTION: Fix the processed file by ensuring all NaN are imputed
# This mimics what STREAMLINE should do but ensures it's done correctly

def fix_nan_in_processed_file(df_processed, cat_features=None, quant_features=None):
    """
    Comprehensive NaN fixing function that handles all cases
    """
    df_fixed = df_processed.copy()
    
    # Identify feature types if not provided
    if cat_features is None or quant_features is None:
        # Boolean columns are categorical
        bool_cols = df_fixed.select_dtypes(include=['bool']).columns.tolist()
        # Integer columns that are not boolean
        int_cols = df_fixed.select_dtypes(include=['int64']).columns.tolist()
        # Float columns (these might have NaN)
        float_cols = df_fixed.select_dtypes(include=['float64']).columns.tolist()
        
        # Remove non-feature columns
        non_feature_cols = ['sample_id', 'label', 'Class']
        bool_cols = [c for c in bool_cols if c not in non_feature_cols]
        int_cols = [c for c in int_cols if c not in non_feature_cols]
        float_cols = [c for c in float_cols if c not in non_feature_cols]
        
        cat_features = bool_cols + [c for c in int_cols if df_fixed[c].nunique() <= 10]  # Heuristic
        quant_features = float_cols + [c for c in int_cols if c not in cat_features]
    
    print(f"Categorical features: {len(cat_features)}")
    print(f"Quantitative features: {len(quant_features)}")
    
    # Step 1: Impute categorical with mode
    print("\nImputing categorical features...")
    for col in cat_features:
        if col in df_fixed.columns and df_fixed[col].isna().sum() > 0:
            mode_val = df_fixed[col].mode()
            fill_val = mode_val[0] if len(mode_val) > 0 else False  # False for bool, 0 for int
            if pd.isna(fill_val):
                fill_val = False if df_fixed[col].dtype == 'bool' else 0
            df_fixed[col].fillna(fill_val, inplace=True)
    
    # Step 2: Impute quantitative with median
    print("Imputing quantitative features...")
    for col in quant_features:
        if col in df_fixed.columns and df_fixed[col].isna().sum() > 0:
            median_val = df_fixed[col].median()
            fill_val = median_val if not pd.isna(median_val) else 0
            df_fixed[col].fillna(fill_val, inplace=True)
    
    # Step 3: Final pass - handle any remaining NaN
    print("Final pass - handling any remaining NaN...")
    remaining_nan_cols = df_fixed.columns[df_fixed.isna().any()].tolist()
    for col in remaining_nan_cols:
        if col not in ['sample_id', 'label', 'Class']:
            if df_fixed[col].dtype == 'bool':
                df_fixed[col].fillna(False, inplace=True)
            elif df_fixed[col].dtype in ['int64', 'int32']:
                df_fixed[col].fillna(0, inplace=True)
            else:
                mode_val = df_fixed[col].mode()
                fill_val = mode_val[0] if len(mode_val) > 0 else 0
                df_fixed[col].fillna(fill_val, inplace=True)
    
    return df_fixed

# Apply the fix
print("=== Applying Comprehensive NaN Fix ===")
df_fixed = fix_nan_in_processed_file(df_processed)

print(f"\n✅ NaN count after fix: {df_fixed.isna().sum().sum()}")
print(f"✅ All NaN values handled!")

# Verify no NaN remain
if df_fixed.isna().sum().sum() == 0:
    print("\n🎉 SUCCESS: All NaN values have been imputed!")
else:
    print(f"\n⚠️ WARNING: {df_fixed.isna().sum().sum()} NaN values still remain")
    print("Remaining NaN columns:", df_fixed.columns[df_fixed.isna().any()].tolist())

In [ ]:
# Save the fixed file (uncomment to save)
output_path = '/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test_Processed_FIXED.csv'

# Uncomment the next two lines to save:
# df_fixed.to_csv(output_path, index=False)
# print(f"\n✅ Fixed file saved to: {output_path}")

print("\nTo use this fixed file:")
print("1. Replace the original Processed.csv with this fixed version")
print("2. OR modify model_replicate.py to ensure imputation runs correctly")
print("3. OR pre-process test data to match training format exactly")

In [ ]:
df.isnull().sum()

sample_id    0
SNP_0        0
SNP_1        0
SNP_2        0
SNP_3        0
            ..
SNP_56713    0
SNP_56714    0
SNP_56715    0
SNP_56716    0
label        0
Length: 56719, dtype: int64

In [ ]:
# 1. Check if there are any NaNs at all
print("Any NaNs?", df.isna().any().any())

Any NaNs? False

In [ ]:
df2 = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test_Processed.csv')

In [ ]:
df2.head()

,sample_id,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_56699_0,SNP_56699_1,SNP_56699_2,SNP_56700_0,SNP_56700_1,SNP_56700_2,SNP_56700_3,SNP_56716_0,SNP_56716_1,SNP_56716_2
0,GCA_025789855.2,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
1,ERR4035462,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
2,GCA_025782975.2,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
3,ERR1218605,0,0,0,1,0,0,1,0,0,...,False,False,True,False,False,True,0,0,0,0
4,GCA_023881545.1,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0

In [ ]:
df = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/exploratory/DataProcessSummary.csv')
df.head()

,Unnamed: 0,Instances,Total Features,Categorical Features,Quantitative Features,Missing Values,Missing Percent,Class 0,Class 1
0,Original,118.0,56717.0,56717.0,0.0,0.0,0.00000,63.0,55.0
1,C1,118.0,56717.0,56717.0,0.0,470.0,0.00007,63.0,55.0
2,R1,118.0,67259.0,67259.0,0.0,470.0,0.00006,63.0,55.0

In [2]:
df = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test_Processed.csv')

In [4]:
df.isnull().sum().sum()

470

In [ ]:
df.isnull().sum().sort_values(ascending=False).head(20)

SNP_6296     3
SNP_55367    3
SNP_54029    3
SNP_54800    2
SNP_42048    2
SNP_10002    2
SNP_8534     2
SNP_13299    2
SNP_44646    2
SNP_52952    2
SNP_20212    2
SNP_7723     2
SNP_54034    2
SNP_12816    2
SNP_43745    2
SNP_45368    2
SNP_55839    2
SNP_48827    2
SNP_20369    2
SNP_33137    2
dtype: int64

In [6]:
df = df.fillna(0)

In [7]:
df.isnull().sum().sum()

0

In [8]:
df.to_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test.csv', index=False)

In [11]:
df2 = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPRepData/SNP_merged_test.csv')

In [10]:
df2.isnull().sum().sum()

0

In [ ]:
df2.head()

,sample_id,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_56699_0,SNP_56699_1,SNP_56699_2,SNP_56700_0,SNP_56700_1,SNP_56700_2,SNP_56700_3,SNP_56716_0,SNP_56716_1,SNP_56716_2
0,GCA_025789855.2,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
1,ERR4035462,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
2,GCA_025782975.2,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
3,ERR1218605,0,0,0,1,0,0,1,0,0,...,False,False,True,False,False,True,0,0,0,0
4,GCA_023881545.1,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0

In [13]:
df2.shape

(118, 67261)

In [14]:
import pandas as pd

# Load datasets
print("Loading training dataset...")
train_df = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPData/SNP_merged_train.csv')
print(f"Training dataset shape: {train_df.shape}")
print(f"Training dataset columns: {len(train_df.columns)}")

print("\nLoading test/replication dataset...")
test_df = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPRepData/SNP_merged_test.csv')
print(f"Test dataset shape: {test_df.shape}")
print(f"Test dataset columns: {len(test_df.columns)}")

# Get feature lists (excluding label and instance columns)
train_features = set(train_df.columns) - {'label', 'sample_id'}
test_features = set(test_df.columns) - {'label', 'sample_id'}

print(f"\nTraining features: {len(train_features)}")
print(f"Test features: {len(test_features)}")

# Find missing features
missing_in_test = train_features - test_features
extra_in_test = test_features - train_features

print(f"\nMissing in test dataset: {len(missing_in_test)} features")
if len(missing_in_test) > 0:
    print(f"First 20 missing: {sorted(list(missing_in_test))[:20]}")

print(f"\nExtra in test dataset: {len(extra_in_test)} features")
if len(extra_in_test) > 0:
    print(f"First 20 extra: {sorted(list(extra_in_test))[:20]}")

# Check if test has all training features
if missing_in_test:
    print(f"\n❌ ERROR: Test dataset is missing {len(missing_in_test)} features from training dataset!")
else:
    print("\n✅ Test dataset has all features from training dataset!")

Loading training dataset...
Training dataset shape: (470, 56719)
Training dataset columns: 56719

Loading test/replication dataset...
Test dataset shape: (118, 67261)
Test dataset columns: 67261

Training features: 56717
Test features: 67259

Missing in test dataset: 5156 features
First 20 missing: ['SNP_10004', 'SNP_10005', 'SNP_10008', 'SNP_10016', 'SNP_1002', 'SNP_10030', 'SNP_10049', 'SNP_10055', 'SNP_10059', 'SNP_10063', 'SNP_1007', 'SNP_10074', 'SNP_10083', 'SNP_10096', 'SNP_10112', 'SNP_10119', 'SNP_10137', 'SNP_10144', 'SNP_1015', 'SNP_10152']

Extra in test dataset: 15698 features
First 20 extra: ['SNP_10004_0', 'SNP_10004_1', 'SNP_10004_2', 'SNP_10005_0', 'SNP_10005_1', 'SNP_10005_2', 'SNP_10008_0', 'SNP_10008_1', 'SNP_10008_2', 'SNP_10016_0', 'SNP_10016_1', 'SNP_10016_2', 'SNP_1002_0', 'SNP_1002_1', 'SNP_1002_2', 'SNP_10030_0', 'SNP_10030_1', 'SNP_10030_2', 'SNP_10049_0', 'SNP_10049_1']

❌ ERROR: Test dataset is missing 5156 features from training dataset!

In [2]:
import pandas as pd
from pathlib import Path

# Paths
x_snp_path = '/Users/921623492/Ecoli_Project/ML/Data/X_snp.csv'
y_labels_path = '/Users/921623492/Ecoli_Project/ML/Data/y_labels.csv'
train_path = '/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPData/SNP_merged_train.csv'
test_output_path = '/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPRepData/SNP_merged_test.csv'

print("=" * 60)
print("EXTRACTING TEST SET FROM ORIGINAL DATA")
print("=" * 60)

# Load existing training set
print("\n📂 Loading existing training set...")
train_df = pd.read_csv(train_path)
train_sample_ids = set(train_df['sample_id'].values)
print(f"   ✅ Training set has {len(train_df):,} samples")

# Load original datasets
print("\n📂 Loading original X_snp.csv...")
try:
    X_snp = pd.read_csv(x_snp_path, index_col=0)
    X_snp.reset_index(inplace=True)
    if X_snp.columns[0] != 'sample_id':
        X_snp.rename(columns={X_snp.columns[0]: 'sample_id'}, inplace=True)
except:
    X_snp = pd.read_csv(x_snp_path)
    if 'sample_id' not in X_snp.columns:
        X_snp.rename(columns={X_snp.columns[0]: 'sample_id'}, inplace=True)

print("\n📂 Loading y_labels.csv...")
y_labels = pd.read_csv(y_labels_path)

# Merge original datasets
print("\n🔗 Merging original features and labels...")
original_df = pd.merge(X_snp, y_labels, on='sample_id', how='inner')
print(f"   ✅ Original dataset: {len(original_df):,} samples")

# Find test samples (samples NOT in training set)
print("\n🔍 Finding test samples (samples not in training set)...")
test_df = original_df[~original_df['sample_id'].isin(train_sample_ids)].copy()
print(f"   ✅ Found {len(test_df):,} test samples")

# Verify
print(f"\n📊 Verification:")
print(f"   Training samples: {len(train_df):,}")
print(f"   Test samples: {len(test_df):,}")
print(f"   Total: {len(train_df) + len(test_df):,}")
print(f"   Original dataset: {len(original_df):,}")

if len(train_df) + len(test_df) != len(original_df):
    print(f"   ⚠️  Warning: Some samples may be missing!")
else:
    print(f"   ✅ All samples accounted for!")

# Check class distribution in test set
print("\n📊 Test set class distribution:")
test_class_counts = test_df['label'].value_counts().sort_index()
for class_val, count in test_class_counts.items():
    pct = (count / len(test_df)) * 100
    print(f"   Class {class_val}: {count:,} samples ({pct:.1f}%)")

# Ensure columns match training set order
print("\n🔧 Ensuring column order matches training set...")
test_df = test_df[train_df.columns]
print(f"   ✅ Columns match training set format")

# Create output directory
Path(test_output_path).parent.mkdir(parents=True, exist_ok=True)

# Save test set
print(f"\n💾 Saving test set: {test_output_path}")
test_df.to_csv(test_output_path, index=False)
print(f"   ✅ Saved {len(test_df):,} samples with {len(test_df.columns)-2:,} features")

print("\n" + "=" * 60)
print("✅ TEST SET EXTRACTION COMPLETE!")
print("=" * 60)
print(f"\nTest set saved to: {test_output_path}")
print(f"\nThe test set should now match the training set format and be ready for STREAMLINE!")

============================================================
EXTRACTING TEST SET FROM ORIGINAL DATA
============================================================

📂 Loading existing training set...
   ✅ Training set has 470 samples

📂 Loading original X_snp.csv...

📂 Loading y_labels.csv...

🔗 Merging original features and labels...
   ✅ Original dataset: 588 samples

🔍 Finding test samples (samples not in training set)...
   ✅ Found 118 test samples

📊 Verification:
   Training samples: 470
   Test samples: 118
   Total: 588
   Original dataset: 588
   ✅ All samples accounted for!

📊 Test set class distribution:
   Class R: 55 samples (46.6%)
   Class S: 63 samples (53.4%)

🔧 Ensuring column order matches training set...
   ✅ Columns match training set format

💾 Saving test set: /Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPRepData/SNP_merged_test.csv
   ✅ Saved 118 samples with 56,717 features

============================================================
✅ TEST SET EXTRACTION COMPLETE!
============================================================

Test set saved to: /Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPRepData/SNP_merged_test.csv

The test set should now match the training set format and be ready for STREAMLINE!

In [3]:
df = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPRepData/SNP_merged_test.csvdf')

In [ ]:
df.shape

(118, 56719)

Part II

In [1]:
import pandas as pd

df = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test_Processed.csv')

In [2]:
df.head()

df.shape 

df.isnull().sum().sum()

470

In [ ]:
df.head()

,sample_id,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_56699_0,SNP_56699_1,SNP_56699_2,SNP_56700_0,SNP_56700_1,SNP_56700_2,SNP_56700_3,SNP_56716_0,SNP_56716_1,SNP_56716_2
0,ERR1218582,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
1,ERR1218605,0,0,0,1,0,0,1,0,0,...,False,False,True,False,False,True,0,0,0,0
2,ERR1218607,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
3,ERR1218623,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
4,ERR1218646,0,1,1,1,0,0,1,0,0,...,False,True,False,False,True,False,0,0,0,0

In [4]:
df.isna().any().any()

True

In [5]:
nan_cols = df.isna().sum()
nan_cols[nan_cols > 0].sort_values(ascending=False)

SNP_55367    3
SNP_54029    3
SNP_6296     3
SNP_48827    2
SNP_25264    2
            ..
SNP_20174    1
SNP_20141    1
SNP_20085    1
SNP_19763    1
SNP_21880    1
Length: 433, dtype: int64

In [6]:
df['SNP_55367']

0      1.0
1      2.0
2      1.0
3      1.0
4      1.0
      ...
113    2.0
114    1.0
115    1.0
116    1.0
117    1.0
Name: SNP_55367, Length: 118, dtype: float64

In [7]:
df[df.isna().any(axis=1)]

,sample_id,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_56699_0,SNP_56699_1,SNP_56699_2,SNP_56700_0,SNP_56700_1,SNP_56700_2,SNP_56700_3,SNP_56716_0,SNP_56716_1,SNP_56716_2
1,ERR1218605,0,0,0,1,0,0,1,0,0,...,False,False,True,False,False,True,0,0,0,0
5,ERR1218651,0,0,1,1,0,0,0,0,0,...,False,True,False,False,True,False,0,0,0,0
6,ERR1218703,0,0,1,1,0,0,1,0,0,...,False,True,False,False,True,False,0,0,0,0
9,ERR4034463,0,0,0,1,1,0,1,0,0,...,False,True,False,False,True,False,0,0,0,0
10,ERR4034645,0,0,1,1,0,1,0,0,0,...,False,True,False,False,True,False,0,0,0,0
11,ERR4034796,0,0,1,1,0,0,0,0,0,...,False,True,False,True,False,False,0,0,0,0
12,ERR4034921,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
14,ERR4035089,0,0,0,1,1,0,1,1,1,...,True,False,False,True,False,False,0,0,0,0
15,ERR4035092,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
21,ERR4035362,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
24,ERR4035469,0,1,1,1,0,0,0,0,0,...,False,True,False,False,True,False,0,0,0,0
25,ERR4035503,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
28,ERR4035750,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
34,ERR4036593,0,1,0,1,0,0,1,0,0,...,False,False,True,False,False,True,0,0,0,0
40,ERR4036861,0,0,1,1,0,0,0,0,0,...,False,True,False,True,False,False,0,0,0,0
43,ERR4037145,0,1,1,1,0,0,0,0,0,...,False,True,False,False,True,False,0,0,0,0
44,ERR4037189,1,1,1,1,0,1,0,0,0,...,False,True,False,False,True,False,0,0,0,0
49,ERR434439,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
50,ERR434515,1,1,1,1,0,0,1,0,0,...,False,True,False,False,True,False,0,0,0,0
51,ERR434647,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
59,ERR435043,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
62,ERR435119,0,0,0,1,0,0,1,0,0,...,False,False,True,False,False,True,0,0,0,0
66,ERR435280,0,1,1,0,0,0,0,0,0,...,False,False,True,False,False,True,0,0,0,0
68,ERR435456,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
69,ERR435487,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
77,GCA_023858485.1,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
78,GCA_023860145.1,0,0,1,1,0,0,0,0,0,...,False,True,False,False,True,False,0,0,0,0
82,GCA_023863365.1,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
83,GCA_023865455.1,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
84,GCA_023866075.1,0,1,0,1,0,0,1,0,0,...,False,False,True,False,False,True,0,0,0,0
88,GCA_023870625.1,0,0,1,1,0,0,0,0,0,...,False,True,False,False,True,False,0,0,0,0
89,GCA_023871245.1,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
90,GCA_023871565.1,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
92,GCA_023876675.1,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
95,GCA_023878305.1,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
96,GCA_023881545.1,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
97,GCA_023881905.1,0,0,1,1,0,0,0,0,0,...,False,True,False,True,False,False,0,0,0,0
99,GCA_023884905.1,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
102,GCA_023889995.1,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
103,GCA_023890185.1,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
105,GCA_023895535.1,0,0,1,1,0,0,0,0,0,...,False,True,False,False,True,False,0,0,0,0
106,GCA_023895655.1,0,0,0,1,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
107,GCA_025579285.2,0,0,0,1,1,0,1,0,0,...,False,True,False,False,True,False,0,0,0,0
108,GCA_025580685.2,0,0,1,1,0,0,0,0,0,...,False,True,False,False,True,False,0,0,0,0
109,GCA_025581085.2,0,0,1,1,0,0,1,0,0,...,False,True,False,False,True,False,0,0,0,0
111,GCA_025783535.2,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0
117,GCA_025789855.2,0,0,0,0,1,0,1,1,1,...,False,True,False,False,True,False,0,0,0,0

In [9]:
(df.isna().any(axis=1)).sum()

47

In [10]:
df = df.fillna(0)

In [ ]:
df.isnull().sum().sum()

0

In [13]:
df = df.replace({True: 1, False: 0})

/tmp/ipykernel_642296/2180546242.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({True: 1, False: 0})

In [ ]:
df.head()

,sample_id,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_56699_0,SNP_56699_1,SNP_56699_2,SNP_56700_0,SNP_56700_1,SNP_56700_2,SNP_56700_3,SNP_56716_0,SNP_56716_1,SNP_56716_2
0,ERR1218582,0,0,0,1,1,0,1,1,1,...,0,1,0,0,1,0,0,0,0,0
1,ERR1218605,0,0,0,1,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0
2,ERR1218607,0,0,0,1,1,0,1,1,1,...,0,1,0,0,1,0,0,0,0,0
3,ERR1218623,0,0,0,1,1,0,1,1,1,...,0,1,0,0,1,0,0,0,0,0
4,ERR1218646,0,1,1,1,0,0,1,0,0,...,0,1,0,0,1,0,0,0,0,0

In [16]:
# Make sure all SNP columns are ints
for col in df.columns:
    if col != "sample_id" and col != "label":
        df[col] = df[col].astype(int)

In [19]:
print("Any NaNs left?", df.isna().any().any())

Any NaNs left? False

In [20]:

df.to_csv("SNP_merged_test_Processed_CLEAN.csv", index=False)

In [ ]:
pwd

'/Users/921623492/Ecoli_Project/ML/Final_ML_02'

In [22]:
import pandas as pd
import numpy as np

# Load the cleaned file
df_clean = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/SNP_merged_test_Processed_CLEAN.csv')

# Load training data to compare
df_train = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPData/SNP_merged_train.csv')

print("=" * 60)
print("VERIFICATION CHECKLIST")
print("=" * 60)

# 1. Check required columns
print("\n1. REQUIRED COLUMNS:")
print(f"   ✓ Has 'label' column: {'label' in df_clean.columns}")
print(f"   ✓ Has 'sample_id' column: {'sample_id' in df_clean.columns}")

# 2. Check for NaN values
print("\n2. MISSING VALUES CHECK:")
nan_count = df_clean.isna().sum().sum()
print(f"   ✓ Total NaN values: {nan_count}")
if nan_count > 0:
    print("   ⚠️  WARNING: File contains NaN values!")
    print("   Columns with NaN:")
    nan_cols = df_clean.columns[df_clean.isna().any()].tolist()
    for col in nan_cols[:10]:  # Show first 10
        print(f"      - {col}: {df_clean[col].isna().sum()} NaN")
else:
    print("   ✓ No NaN values found!")

# 3. Check feature matching with training data
print("\n3. FEATURE MATCHING:")
train_features = set(df_train.columns) - {'label', 'sample_id'}
clean_features = set(df_clean.columns) - {'label', 'sample_id'}
missing_features = train_features - clean_features
extra_features = clean_features - train_features

print(f"   Training features: {len(train_features)}")
print(f"   Clean file features: {len(clean_features)}")
if missing_features:
    print(f"   ⚠️  MISSING {len(missing_features)} features from training data:")
    for feat in list(missing_features)[:10]:
        print(f"      - {feat}")
else:
    print("   ✓ All training features present!")
    
if extra_features:
    print(f"   ℹ️  Extra features in clean file: {len(extra_features)} (OK, will be ignored)")

# 4. Check data types
print("\n4. DATA TYPES:")
feature_cols = [c for c in df_clean.columns if c not in ['label', 'sample_id']]
non_numeric = []
for col in feature_cols[:100]:  # Check first 100 features
    if not pd.api.types.is_numeric_dtype(df_clean[col]):
        non_numeric.append(col)

if non_numeric:
    print(f"   ⚠️  Found {len(non_numeric)} non-numeric feature columns:")
    for col in non_numeric[:10]:
        print(f"      - {col}: {df_clean[col].dtype}")
else:
    print("   ✓ All feature columns are numeric!")

# 5. Check shape
print("\n5. DATA SHAPE:")
print(f"   Rows: {len(df_clean)}")
print(f"   Columns: {len(df_clean.columns)}")

# 6. Check class distribution
print("\n6. CLASS DISTRIBUTION:")
if 'label' in df_clean.columns:
    print(df_clean['label'].value_counts())

print("\n" + "=" * 60)
print("SUMMARY:")
if nan_count == 0 and len(missing_features) == 0:
    print("✅ FILE IS READY FOR MODEL EVALUATION!")
else:
    print("⚠️  FILE NEEDS FIXES BEFORE USE")
print("=" * 60)

============================================================
VERIFICATION CHECKLIST
============================================================

1. REQUIRED COLUMNS:
   ✓ Has 'label' column: True
   ✓ Has 'sample_id' column: True

2. MISSING VALUES CHECK:
   ✓ Total NaN values: 0
   ✓ No NaN values found!

3. FEATURE MATCHING:
   Training features: 56717
   Clean file features: 67259
   ⚠️  MISSING 5156 features from training data:
      - SNP_34429
      - SNP_38145
      - SNP_45243
      - SNP_18275
      - SNP_38165
      - SNP_37203
      - SNP_1971
      - SNP_54197
      - SNP_54474
      - SNP_34902
   ℹ️  Extra features in clean file: 15698 (OK, will be ignored)

4. DATA TYPES:
   ✓ All feature columns are numeric!

5. DATA SHAPE:
   Rows: 118
   Columns: 67261

6. CLASS DISTRIBUTION:
label
1    63
0    55
Name: count, dtype: int64

============================================================
SUMMARY:
⚠️  FILE NEEDS FIXES BEFORE USE
============================================================

In [23]:
import pandas as pd
import numpy as np

# Load the cleaned test file
df_clean = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/SNP_merged_test_Processed_CLEAN.csv')

# Load PROCESSED training data (from CV dataset - this is what STREAMLINE actually uses)
df_train_processed = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/CVDatasets/SNP_merged_train_CV_0_Train.csv')

print("=" * 60)
print("VERIFICATION CHECKLIST (vs PROCESSED Training Data)")
print("=" * 60)

# 1. Check required columns
print("\n1. REQUIRED COLUMNS:")
print(f"   ✓ Has 'label' column: {'label' in df_clean.columns}")
print(f"   ✓ Has 'sample_id' column: {'sample_id' in df_clean.columns}")

# 2. Check for NaN values
print("\n2. MISSING VALUES CHECK:")
nan_count = df_clean.isna().sum().sum()
print(f"   ✓ Total NaN values: {nan_count}")
if nan_count > 0:
    print("   ⚠️  WARNING: File contains NaN values!")
else:
    print("   ✓ No NaN values found!")

# 3. Check feature matching with PROCESSED training data
print("\n3. FEATURE MATCHING (vs PROCESSED Training):")
train_features = set(df_train_processed.columns) - {'label', 'sample_id'}
clean_features = set(df_clean.columns) - {'label', 'sample_id'}
missing_features = train_features - clean_features
extra_features = clean_features - train_features

print(f"   Processed training features: {len(train_features)}")
print(f"   Clean file features: {len(clean_features)}")
if missing_features:
    print(f"   ⚠️  MISSING {len(missing_features)} features from processed training data:")
    for feat in list(missing_features)[:10]:
        print(f"      - {feat}")
else:
    print("   ✓ All processed training features present!")
    
if extra_features:
    print(f"   ℹ️  Extra features in clean file: {len(extra_features)} (OK, will be ignored)")

# 4. Check data types
print("\n4. DATA TYPES:")
feature_cols = [c for c in df_clean.columns if c not in ['label', 'sample_id']]
non_numeric = []
for col in feature_cols[:100]:  # Check first 100 features
    if not pd.api.types.is_numeric_dtype(df_clean[col]):
        non_numeric.append(col)

if non_numeric:
    print(f"   ⚠️  Found {len(non_numeric)} non-numeric feature columns:")
    for col in non_numeric[:10]:
        print(f"      - {col}: {df_clean[col].dtype}")
else:
    print("   ✓ All feature columns are numeric!")

# 5. Check shape
print("\n5. DATA SHAPE:")
print(f"   Rows: {len(df_clean)}")
print(f"   Columns: {len(df_clean.columns)}")

# 6. Check class distribution
print("\n6. CLASS DISTRIBUTION:")
if 'label' in df_clean.columns:
    print(df_clean['label'].value_counts())

print("\n" + "=" * 60)
print("SUMMARY:")
if nan_count == 0 and len(missing_features) == 0:
    print("✅ FILE IS READY FOR MODEL EVALUATION!")
else:
    print("⚠️  FILE NEEDS FIXES BEFORE USE")
    if len(missing_features) > 0:
        print(f"   - Missing {len(missing_features)} features from processed training data")
    if nan_count > 0:
        print(f"   - Contains {nan_count} NaN values")
print("=" * 60)

============================================================
VERIFICATION CHECKLIST (vs PROCESSED Training Data)
============================================================

1. REQUIRED COLUMNS:
   ✓ Has 'label' column: True
   ✓ Has 'sample_id' column: True

2. MISSING VALUES CHECK:
   ✓ Total NaN values: 0
   ✓ No NaN values found!

3. FEATURE MATCHING (vs PROCESSED Training):
   Processed training features: 5000
   Clean file features: 67259
   ✓ All processed training features present!
   ℹ️  Extra features in clean file: 62259 (OK, will be ignored)

4. DATA TYPES:
   ✓ All feature columns are numeric!

5. DATA SHAPE:
   Rows: 118
   Columns: 67261

6. CLASS DISTRIBUTION:
label
1    63
0    55
Name: count, dtype: int64

============================================================
SUMMARY:
✅ FILE IS READY FOR MODEL EVALUATION!
============================================================

In [24]:
import pandas as pd
import pickle

# Load your cleaned processed file
processed_path = '/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/SNP_merged_test_Processed.csv'
df = pd.read_csv(processed_path)

# Load training metadata to get categorical/quantitative features
train_path = '/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/exploratory/post_processed_features.pickle'
with open(train_path, 'rb') as f:
    train_features = pickle.load(f)

# Determine categorical vs quantitative (you may need to adjust this logic)
# For now, we'll create minimal metadata
feature_cols = [c for c in df.columns if c not in ['label', 'sample_id']]

# Create categorical_features.pickle (empty list or based on your data)
categorical_features = []  # Adjust based on your actual categorical features
with open('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/exploratory/categorical_features.pickle', 'wb') as f:
    pickle.dump(categorical_features, f)

# Create post_processed_features.pickle
with open('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/Abdoul_Output/Abdoul_thesis/SNP_merged_train/replication/SNP_merged_test/exploratory/post_processed_features.pickle', 'wb') as f:
    pickle.dump(feature_cols, f)

In [4]:
df_test = pd.read_csv('/Users/921623492/Ecoli_Project/ML/Final_ML_02/STREAMLINE/data/SNPRepData/SNP_merged_test.csv')

In [ ]:
df_test.head()

,sample_id,SNP_0,SNP_1,SNP_2,SNP_3,SNP_4,SNP_5,SNP_6,SNP_7,SNP_8,...,SNP_56708,SNP_56709,SNP_56710,SNP_56711,SNP_56712,SNP_56713,SNP_56714,SNP_56715,SNP_56716,label
0,ERR1218582,0,0,0,1,1,0,1,1,1,...,0,1,1,1,0,1,1,0,2,R
1,ERR1218605,0,0,0,1,0,0,1,0,0,...,0,0,1,1,0,1,1,1,1,R
2,ERR1218607,0,0,0,1,1,0,1,1,1,...,0,1,1,1,0,1,1,0,2,R
3,ERR1218623,0,0,0,1,1,0,1,1,1,...,0,1,1,1,0,1,1,0,2,R
4,ERR1218646,0,1,1,1,0,0,1,0,0,...,0,0,1,1,0,1,1,1,1,R

In [6]:
df_test.isnull().sum().sum()

0

In [7]:
df_test.nunique()

sample_id    118
SNP_0          2
SNP_1          2
SNP_2          2
SNP_3          2
            ...
SNP_56713      2
SNP_56714      2
SNP_56715      2
SNP_56716      2
label          2
Length: 56719, dtype: int64

In [9]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Columns: 56719 entries, sample_id to label
dtypes: int64(56717), object(2)
memory usage: 51.1+ MB